modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL = "https://github.com/NikitaCartes/Return-my-gold-farm/issues"

[[mods]]
modId = "returnmygoldfarm"
version = "${version}"
displayName = "Return my gold farm"
displayURL = "https://github.com/NikitaCartes/Return-my-gold-farm"
authors = "NikitaCartes"
description = '''
Drop XP and gold from zombified piglins even if they weren't killed by a player
'''
logoFile = "assets/return-my-gold-farm/icon.png"

[[mixins]]
config = "return-my-gold-farm.mixins.json"

[[dependencies.returnmygoldfarm]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.returnmygoldfarm]]
modId = "minecraft"
type = "required"
versionRange = "${supported_minecraft_version}"
ordering = "NONE"
side = "BOTH"
